# Generated by Django 5.0.3 on 2024-04-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='postal_code',
            new_name='post_code',
        ),
    ]
